### ISSUE TITLE
auxiliary function for load file

### ISSUE THREAD

**Issue by arademaker** [Rudolph-Miller/jonathan#17]
Does this library has any auxiliary function to read from a file?

**Comment by rudolph-miller** [comment]
Currently, no, it can only handle strings.
I plan to support pathnames and steams.

`(parse (alexandria:read-file-into-string "pathname"))`

**Comment by arademaker** [comment]
With a 150MB file:

Heap exhausted (no more space for allocation).
395870208 bytes available, 536870944 requested.

PROCEED WITH CAUTION.
   [Condition of type SB-KERNEL::HEAP-EXHAUSTED-ERROR]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] abort thread (#<THREAD "repl-thread" RUNNING {1004BC8003}>)

(jonathan:parse (alexandria:read-file-into-string "onepetro.json"))

The problem is the reading of the text file, not the parse!

**Comment by arademaker** [comment]
BTW, mlisp (Allegro Modern Lisp):

```
cl-user> (time (with-open-file (in #P"onepetro.json")
         (length (st-json:read-json in))))
; cpu time (non-gc) 12.014951 sec user, 0.453510 sec system
; cpu time (gc)     6.919787 sec user, 0.259170 sec system
; cpu time (total)  18.934738 sec user, 0.712680 sec system
; cpu time (thread) 11.999369 sec user, 0.439226 sec system
; real time  20.168150 sec (97.42%)
; space allocation:
;  12,748,321 cons cells, 646,417,616 other bytes, 0 static bytes
; Page Faults: major: 489 (gc: 113026), minor: 227839 (gc: 113026)
166942
```

In SBCL it killed the SBCL proc.

**Comment by rudolph-miller** [comment]
Hmm, it can be solved by using streams, and it can be time to add support of streams.

Before then, you can avoid the problem with using like http://www.sbcl.org/manual/#Runtime-Options (SBCL).

**Comment by arademaker** [comment]
Jonathan didn't work in mlisp! Thanks, I will try.

**Comment by rudolph-miller** [comment]
Thank you for reporting of your use case : )

**Comment by arademaker** [comment]
Not sure which parameter to try. With the command below I still got error:

```
sbcl --control-stack-size 10 --dynamic-space-size 5000
```

**Comment by rudolph-miller** [comment]
`--dynastic-space-size`is the correct option.
Didn't it make some change to the error message?
Like `~ bytes available`.
