### ISSUE TITLE
[sbcl] Problems with compiling jonathan

### ISSUE THREAD

**Issue by maximvl** [Rudolph-Miller/jonathan#19]
Hi, I wanted to check out clack, but it depends on jonathan and I got this while compiling:

```
1 compiler notes:

quicklisp/dists/quicklisp/software/jonathan-20150505-git/src/util.lisp:31:19:
  read-error: 
    READ error during COMPILE-FILE:

      Lock on package SB-IMPL violated when interning COMMA-P while in package
      JONATHAN.UTIL.

      (in form starting at line: 27, column: 42, file-position: 661)

Compilation failed.
```

I have SBCL 1.1.14.debian installed, but I had same problem on newer versions too.

**Comment by rudolph-miller** [comment]
In SBCL 1.2.11 there is sb-impl::comma-p, and I did not check it in older version.

Can you try it with the latest version of SBCL?

**Comment by rudolph-miller** [comment]
I now got SBCL 1.1.14, then will try to make it work well with this version of SBCL.

**Comment by maximvl** [comment]
@Rudolph-Miller I think you shouldn't worry about 1.1.*, this is just what I had at hand. I will share my issue with latest SBCL later.

**Comment by rudolph-miller** [comment]
Okay, that's too old.
It's easy to manage versions of SBCL via [Roswell](https://github.com/snmsts/roswell).

**Comment by maximvl** [comment]
@Rudolph-Miller I updated quicklisp systems list and everything works fine now, sorry for disturbing, feel free to close this issue)

**Comment by rudolph-miller** [comment]
Okay, have fun to play Clack. :smile:

**Comment by BMarkmann** [comment]
I'm hitting this same issue, trying to install caveman2 with quicklisp.  

> Lock on package SB-IMPL violated when interning COMMA-P while in package JONATHAN.UTIL.

I've done a (ql:update-all-dists) and (ql:update-client) as @maximvl suggested above, but still run into the issue.  I'm running SBCL 1.1.1.14 (most recent in Ubuntu apt repo).  Any idea how to get around this?

**Comment by rudolph-miller** [comment]
You should update your SBCL and it'll work well.

If you have a problem to update your SBCL, consider to use [Roswell](https://github.com/snmsts/roswell).

**Comment by BMarkmann** [comment]
That worked.  It seems like Ubuntu hasn't moved to 1.2.x for SBCL.  Thanks for the help!

**Comment by rudolph-miller** [comment]
Nice to hear that. :)
