### ISSUE TITLE
Error parsing empty object

### ISSUE THREAD

**Issue by orthecreedence** [Rudolph-Miller/jonathan#20]
Started converting [cl-rethinkdb](https://github.com/orthecreedence/cl-rethinkdb) and [Turtl's api](https://github.com/turtl/api) to jonathan. So far, cool library! I'm getting an error (using the latest git version):

``` lisp
(jonathan:parse "{\"name\":{}}")
```

triggers `Unexpected EOF found: {"user":{}} [Condition of type JONATHAN.ERROR:<JONATHAN-UNEXPECTED-EOF-ERROR>]`

Also, as a side note, `(jonathan:parse "{}" :as :hash-table)` returns `nil` (I would expect an empty hash table).

Thanks!

**Comment by rudolph-miller** [comment]
Thanks for your using Jonathan and reporting some bugs. :-)

**Comment by rudolph-miller** [comment]
I fix this bug and make `(jonathan:parse "{}" :as :hash-table)` return empty hash-table.

Please check it. :)

**Comment by orthecreedence** [comment]
Working great now, thanks!
