### ISSUE TITLE
Decoding issue

### ISSUE THREAD

**Issue by orthecreedence** [Rudolph-Miller/jonathan#21]
Hello! I have another decoding issue:

``` lisp
(let ((json "{\"storage\":2.305843009213693952e+20}"))
  (jonathan:parse json))
```

triggers `Unexpected EOF found`. Seems it's getting tripped up on the scientific notation.

Thanks!

**Comment by rudolph-miller** [comment]
It seems to be that I forgot to implement kind of e or E notation.
Thanks for your reporting. :)

**Comment by rudolph-miller** [comment]
https://tools.ietf.org/html/rfc7159#section-6

**Comment by rudolph-miller** [comment]
With this commit(https://github.com/Rudolph-Miller/jonathan/commit/455005e9925a236e4320515e3d5204ced5a59d42), jonathan can handle e or E annotation, though it take it as float.
So,

``` Lisp
(let ((json "2.305843009213693952e+20"))
  (jonathan:parse json))
;; => 2.305843e20 (same as yason:parse)
```

.

Does it suit you?
If you want it to support more precise float, feel free to ask me; I'll try to implement in some ways. :)

**Comment by orthecreedence** [comment]
This works perfectly! Thanks!

**Comment by rudolph-miller** [comment]
:)
