### ISSUE TITLE
test on some impls

### ISSUE THREAD

**Issue by rudolph-miller** [Rudolph-Miller/jonathan#25]

**Comment by ghost** [comment]
Hi, have you test it on ECL? When I try to quickload it, it reports _"In method definition for %TO-JSON, found an invalid specializer (SIMPLE-VECTOR)"_ when compiling _"encode.lisp"_, but I can't find out where the problem is.

**Comment by rudolph-miller** [comment]
I've not tested yet and plan to test it.

It seems to be the same issue of https://github.com/Rudolph-Miller/jonathan/issues/26.
It's solved, please use the master of this repo. :)

**Comment by ghost** [comment]
Oh I see, thanks! :D
