### ISSUE TITLE
Alists encoded incorrectly

### ISSUE THREAD

**Issue by jorams** [Rudolph-Miller/jonathan#32]
If I take the following JSON and parse it `:as :alist`:

``` json
{
    "test": [{
        "abc": "def",
        "ghi": ""
    }]
}
```

I get the following alist, which is correct.

``` lisp
(("test" (("ghi" . "") ("abc" . "def"))))
```

If I then encode that back to JSON `:from :alist`, what comes out is all wrong.

``` json
{
    "test": {
        "(ghi . )": {
            "abc": "def"
        }
    }
}
```

**Comment by rudolph-miller** [comment]
Thanks for your reporting.

The value of

``` lisp
'(("test" (("ghi" . "") ("abc" . "def"))))
```

for the key `"test"` is

``` lisp
'((("ghi" . "") ("abc" . "def")))
```

, and this can be interpreted as both of

``` lisp
(list (list (cons "ghi" "") (cons "abc" "def")))
```

and

``` lisp
(list (cons '("ghi" . "") (list (cons "abc" "def"))))
```

.
It's ambiguous.

If you really want to treat this kind of structure,
please use `:as :hash-table` .

``` lisp
(jojo:to-json (jojo:parse "{
    \"test\": [{
        \"abc\": \"def\",
        \"ghi\": \"\"
    }]
}" :as :hash-table))
;; => "{\"test\":[{\"abc\":\"def\",\"ghi\":\"\"}]}"
```

**Comment by jorams** [comment]
Thanks for your response.

I figured it would be the ambiguity, but I think the interpretation could be better. The only valid keys in a JSON object are strings, so the first interpretation is, in the context of JSON encoding, "more valid" than the second.

**Comment by rudolph-miller** [comment]
I know what you say, but I do not implement the feature, because in this case, it will be invalid that has symbols as its keys.
