### ISSUE TITLE
Error when quickloading Jonathan on FreeBSD

### ISSUE THREAD

**Issue by ghost** [Rudolph-Miller/jonathan#39]
I'm trying to install jonathan on my system through quicklisp but, for whatever reason, I keep getting the error below:

```
debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR: Error while trying to load definition
for system jonathan from pathname /usr/home/lucas/quicklisp/dists/quicklisp/software/jonathan-
20151218-git/jonathan.asd: READ error during LOAD: :ASCII stream decoding error on
#<SB-SYS:FD-STREAM for "file /usr/home/lucas/quicklisp/dists/quicklisp/software/jonathan-
20151218-git/README.md" {10057D1623}>: the octet sequence #(227) cannot be decoded.(in
form starting at line: 6, column: 0, position: 95)
```

I'm running SBCL version 1.3.1 and the latest quicklisp (SHA256 4a7a5c2aebe0716417047854267397e24a44d0cce096127411e9ce9ccfeb2c17) on my FreeBSD.

I installed Jonathan successfully on my laptop (which is running Ubuntu 15.10)
using SBCL version 1.2.14.debian (and the latest quicklisp version). Not sure if the problem is in Jonathan or my version of SBCL on
the FreeBSD system.

Has anyone had any such problems?
Jonathan is the only library that has run into trouble so far. :cry: 

EDIT: Specified that the SBCL 1.3.1 is on the FreeBSD system.

**Comment by fukamachi** [comment]
I think the problem has been resolved at https://github.com/Rudolph-Miller/jonathan/commit/e33ba7913ce4c9d764533ea1e98876dd7eeea9db, which was added on Dec 25 since you're using "jonathan-
20151218-git".
Please update the Quicklisp dist by `(ql:update-dist "quicklisp")` and try it again.

**Comment by rudolph-miller** [comment]
@lucastadeu Thanks for your reporting :)

@fukamachi Thank you to reply quickly :)

**Comment by ghost** [comment]
@fukamachi thanks for the reply! But, unfortunately, that did not work for me.
I'm already on the latest quicklisp version:

```
* (ql:update-dist "quicklisp")

You already have the latest version of "quicklisp": 2015-12-18.
NIL
```

**Comment by fukamachi** [comment]
Sorry, as a new Quicklisp dist wasn't released the last month, yours is the latest.
It'll be fixed in the new one (which is probably going to be released this month), so you have to fetch the latest version of Jonathan until then.

**Comment by ghost** [comment]
Ah, I see.
Well, I'l just fetch the latest version as you recommended, then.

Thanks!

I guess we can close this, then :sweat_smile:

**Comment by rudolph-miller** [comment]
:)
