### ISSUE TITLE
%to-json fails on strings which aren't simple

### ISSUE THREAD

**Issue by fisxoj** [Rudolph-Miller/jonathan#40]
I was working on something using `mito` and my strings from postgres were coming back as `(vector character)`s.  Despite there being a `((string string))` method for `%to-json`, it actually requires strings to be `simple-string` in [%write-string](https://github.com/fisxoj/jonathan/blob/4a371f1c6e2b7cb5da434a4acc5246e98f4aac77/src/encode.lisp#L46).

I have a solution that creates two methods, one for `simple-string` that does what the current `string` method does, and another on `string` that prints the string into a new `simple-string`.  I'll post that, shortly.

**Comment by rudolph-miller** [comment]
Thank you to report.
I'll review your pull-request then. :octocat:
