### ISSUE TITLE
Make it possible to normlize keywords in nested objects

### ISSUE THREAD

**Issue by libre-man** [Rudolph-Miller/jonathan#46]
This is useful for many applications as normalizing now means first parsing and then doing a second pass for normalizing which is slower.

**Comment by rudolph-miller** [comment]
@libre-man 
Thanks for your suggestion. :)
Have you tried `:normalize-all` keyword option??
It seems not documented...

**Comment by libre-man** [comment]
Sorry I did not see the option. It solves my problem :)
