### ISSUE TITLE
jonathan-encoder0 when some object is present twice in to-json's input

### ISSUE THREAD

**Issue by svetlyak40wt** [Rudolph-Miller/jonathan#55]
```
CL-USER> (let ((user "bob")) (to-json (list :a user :b user)))
"{\"A\":\"jonathan-encoder0\",\"B\":\"bob\"}"
```

Expected result is:

```
{"A": "bob", "B": "bob"}
```

**Comment by svetlyak40wt** [comment]
Right now workaround is wrapping second value with `format` call to make another string instance:

```
CL-USER> (let ((user "bob")) (to-json (list :a user :b (format nil "~A" user))))
"{\"A\":\"bob\",\"B\":\"bob\"}"
```

**Comment by svetlyak40wt** [comment]
Does somebody have ideas how to fix it?

**Comment by svetlyak40wt** [comment]
Guys?

**Comment by rudolph-miller** [comment]
I will take a look at this issue in the next week or two. :octocat:

**Comment by svetlyak40wt** [comment]
Great! Thank you!

**Comment by svetlyak40wt** [comment]
Hi Rudolph. Are there any news here?

**Comment by svetlyak40wt** [comment]
Rudolph, if you don't have time for this issue, please, tell me and may I'll try to solve it myself and will send a pull.

**Comment by svetlyak40wt** [comment]
This issues was closed half year before by pull https://github.com/Rudolph-Miller/jonathan/pull/56

Thanks to https://12forks.com MVP for pointing to this stale issue!
